name: Node.js Build

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      
      - run: Docker build

      - name: Install dependencies
        run: npm install
        
      - name: Docker build
        run: npm run build
        
      - name: Docker push
        run: npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist/
